title: "Rolando Villca Choque"
description: "Data Science Portfolio – Projects, Insights, and Visualisations"
url: "https://yourusername.github.io"  # Replace with your GitHub username
baseurl: ""  # Leave this empty for personal site
repository: "yourusername/yourrepository"  # Replace accordingly

remote_theme: "mmistakes/minimal-mistakes"

author:
  name: "Rolando Villca Choque"
  avatar: "/assets/profile.jpg"
  bio: "Data Science enthusiast turning data into decisions."
  location: "UK / Bolivia"
  links:
    - label: "GitHub"
      icon: "fab fa-github"
      url: "https://github.com/yourusername"
    - label: "LinkedIn"
      icon: "fab fa-linkedin"
      url: "https://linkedin.com/in/yourprofile"
    - label: "Email"
      icon: "fas fa-envelope"
      url: "mailto:your.email@example.com"

# Navigation menu
nav:
  - title: "Home"
    url: /
  - title: "Projects"
    url: /projects/
  - title: "About"
    url: /about/
  - title: "Contact"
    url: /contact/

# Jekyll plugins supported by GitHub Pages
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-sitemap

# Collections for projects
collections:
  projects:
    output: true
    permalink: /projects/:name/

defaults:
  - scope:
      path: ""
      type: "projects"
    values:
      layout: single
      author_profile: true
      read_time: true
      share: true
      comments: false

# Pagination settings
paginate: 5
paginate_path: "/page:num/"

# Markdown processor
markdown: kramdown
kramdown:
  input: GFM
