# ── _config.yml ──────────────────────────────────────────

title: "Data Science Portfolio"
description: "Data Science Professional Practice"
baseurl: "/Rolando-Villca-DSPP"  # adjust if needed
url: "https://rolando-villca.github.io"

# Choose a light theme:
theme: jekyll-theme-cayman
# OR
# theme: minima

markdown: kramdown
kramdown:
  input: GFM

plugins:
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-emoji

exclude:
  - node_modules
  - vendor
