# ──────────────────────────────────────────────────────────────────────────
# Jekyll config for Amazon Sales & Reviews Analysis project page
# ──────────────────────────────────────────────────────────────────────────

title: "Amazon Sales & Reviews Analysis"
description: "Predicting monthly units sold on Amazon UK from product metadata"

# Swap in the Cayman theme
theme: jekyll-theme-cayman

# Keep markdown + emoji support
markdown: kramdown
kramdown:
  input: GFM

plugins:
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-emoji

# Project path
baseurl: "/Rolando-Villca-DSPP"

exclude:
  - node_modules
  - vendor
