# ──────────────────────────────────────────────────────────────────────────
# Jekyll config for Amazon Sales & Reviews Analysis project page
# ──────────────────────────────────────────────────────────────────────────

# Site settings
title: "Amazon Sales & Reviews Analysis"
description: "Predicting monthly units sold on Amazon UK from product metadata"
# No baseurl needed for a project page under your user site

# Build settings
theme: minima
markdown: kramdown
kramdown:
  input: GFM

# Plugins
plugins:
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-emoji

# Exclude these from the build
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
