# ──────────────────────────────────────────────────────────────────────────
# Basic site config for Jekyll (Project Page)
# ──────────────────────────────────────────────────────────────────────────

title: "Amazon Sales & Reviews Analysis"
description: "Predicting monthly sales volume from Amazon UK product metadata"
# No baseurl needed—this is a project page under your user site
markdown: kramdown
theme: minima

# Enable common plugins (SEO tags, feed, emoji support)
plugins:
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-emoji

# kramdown (GitHub-flavored Markdown)
kramdown:
  input: GFM

# Exclude vendor files (optional)
exclude:
  - node_modules
  - vendor
