# ──────────────────────────────────────────────────────────────────────────
# Jekyll configuration for Amazon Sales & Reviews Analysis project page
# ──────────────────────────────────────────────────────────────────────────

title: "Amazon Sales & Reviews Analysis"
description: "Predicting monthly units sold on Amazon UK from product metadata"

# Use the Minima theme for styling
theme: minima

# GitHub-flavored Markdown via kramdown
markdown: kramdown
kramdown:
  input: GFM

# Enable common Pages plugins
plugins:
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-emoji

# Ensure image paths include your project’s base URL
baseurl: "/Rolando-Villca-DSPP"

# Skip these directories/files during build
exclude:
  - node_modules
  - vendor
