title: "Amazon Sales & Reviews Analysis"
description: "Predicting monthly units sold on Amazon UK from product metadata"

theme: jekyll-theme-slate
markdown: kramdown
kramdown:
  input: GFM

plugins:
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-emoji

baseurl: "/Rolando-Villca-DSPP"
