title: "Data Science Apprenticeship"
description: "Data Science Portfolio - Professional Practice"

theme: jekyll-theme-slate
markdown: kramdown
kramdown:
  input: GFM

plugins:
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-emoji

baseurl: "/Rolando-Villca-DSPP"
