# ── _config.yml ───────────────────────────────────────────────────────────

title: "Amazon Sales & Reviews Analysis"
description: "Dark-mode GitHub Pages layout with midnight theme"

baseurl: "/Rolando-Villca-DSPP"
theme: jekyll-theme-midnight  # ← change to the dark midnight theme

markdown: kramdown
kramdown:
  input: GFM

plugins:
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-emoji

exclude:
  - node_modules
  - vendor
