title: "Amazon Sales & Reviews Analysis"
description: "How can Amazon sales and review data be analysed to extract meaningful business insights?"

theme: jekyll-theme-slate
markdown: kramdown
kramdown:
  input: GFM

plugins:
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-emoji

baseurl: "/Rolando-Villca-DSPP"
