# ──────────────────────────────────────────────────────────────────────────
# Jekyll config for the Amazon Sales & Reviews Analysis project page
# ──────────────────────────────────────────────────────────────────────────

title: "Amazon Sales & Reviews Analysis"
description: "Predicting monthly units sold on Amazon UK from product metadata"

markdown: kramdown
kramdown:
  input: GFM

theme: minima

plugins:
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-emoji

exclude:
  - node_modules
  - vendor
